### ISSUE TITLE
模拟器用图片识别报错

### ISSUE THREAD

**Issue by a3247858** [saint228/DreamMultiDevices#3]
from airtest.core.api import *
connect_device('Android://127.0.0.1:5037/127.0.0.1:62001')
if exists(Template(r"..\img\tpl1566374671903.png", record_pos=(0.077, -0.149), resolution=(2340, 1080))):
    print('sdf')
报错如下：
Traceback (most recent call last):
  File "F:/lyydezdh/GFtest/sss.py", line 8, in <module>
    if exists(Template(r"..\img\tpl1566374671903.png", record_pos=(0.077, -0.149), resolution=(2340, 1080))):
  File "D:\Python\Python37\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\airtest\core\api.py", line 411, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "D:\Python\Python37\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\airtest\core\cv.py", line 59, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "D:\Python\Python37\lib\site-packages\airtest\core\android\android.py", line 218, in snapshot
    screen = self.minicap.get_frame_from_stream()
  File "D:\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 24, in wrapper
    return func(inst, *args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 325, in get_frame_from_stream
    self.frame_gen = self.get_stream()
  File "D:\Python\Python37\lib\site-packages\airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 219, in get_stream
    stopped = next(gen)
  File "D:\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 233, in _get_stream
    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
  File "D:\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 289, in _setup_stream_server
    params, display_info = self._get_params()
  File "D:\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 185, in _get_params
    display_info = self.ori_function()
  File "D:\Python\Python37\lib\site-packages\airtest\core\android\android.py", line 546, in get_display_info
    display_info = self.minicap.get_display_info()
  File "D:\Python\Python37\lib\site-packages\airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 149, in get_display_info
    display_info = json.loads(display_info)
  File "D:\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[04:25:09][DEBUG]<airtest.core.android.adb> D:\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:62001 forward --remove tcp:12601
[04:25:09][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended

**Comment by Sinxs** [comment]
模拟器建议使用android7以上的版本，夜神android5肯定报错




------------------ 原始邮件 ------------------
发件人: "肥罗"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 下午5:18
收件人: "saint228/DreamMultiDevices"<DreamMultiDevices@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [saint228/DreamMultiDevices] 模拟器用图片识别报错 (#3)




Closed #3.
